### PR TITLE
Create Study_MPIMP_Fernie.xlsx

### PR DESCRIPTION
**Pull request by micwij**
**Added study template file**

As mentioned in #64 I added a study template file for our lab. I created a subfolder in community named "MPIMP", to which I would later add other templates. I hope I did everything correctly. I am happy for any feedback!

### CODE REVIEW

**Review by Brilator — COMMENTED** [review]
Just a few suggestions:
- [ ] I'd recommend to move `Parameter [Sample Weight]` to assay. At least if I understand it correctly, that this is the material weight used e.g. for metabolite extraction. 
- [ ] Is `Characteristic [alias]` a specific term in your lab? Isn't this covered by other terms (e.g. identifiers in `Source Name`)?

**Review by Brilator — APPROVED** [review]

**Comment by Brilator** [comment]
I mean, if it's a precise term from an MPI LIMS, you might as well include it. 
This could probably be iterated once people use the template

**Comment by Brilator** [comment]
Feel free to merge the PR yourself once you want to see the changes become live in Swate

**Comment by micwij** [comment]
> I mean, if it's a precise term from an MPI LIMS, you might as well include it. This could probably be iterated once people use the template

That's a good idea. I added it back and will ask for feedback from my lab/institute for future updates.

**Comment by micwij** [comment]
> Feel free to merge the PR yourself once you want to see the changes become live in Swate

Sorry, I am still not very familiar with Github. I think I can't. It says:
"This branch has no conflicts with the base branch
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests."

**Comment by Brilator** [comment]
Sorry, my bad. I'll merge.

**Comment by Brilator** [comment]
Ah shoot, there's an error that slipped my attention. I'll try to fix this soon and let you know.

**Comment by Brilator** [comment]
Found the issue. 
There were different `Term Accession Number`s for the same value ("growth protocol")


Protocol Type | Term Source REF (DPBO:1000161) | Term Accession Number (DPBO:1000161)
-- | -- | --
growth protocol | EFO | http://purl.obolibrary.org/obo/EFO_0003789
growth protocol | EFO | http://purl.obolibrary.org/obo/EFO_0003790
growth protocol | EFO | http://purl.obolibrary.org/obo/EFO_0003791
growth protocol | EFO | http://purl.obolibrary.org/obo/EFO_0003792

**Comment by Brilator** [comment]
Fixed https://github.com/nfdi4plants/Swate-templates/commit/fc782ed2c68893d06cd59ac53c32c5281f3d29fc and already live

**Pull request merged**
