### PR TITLE
Create demo_plant_growth.xlsx

### PR DESCRIPTION
**Pull request by Brilator**
this is a demo template for plant growth, that should align perfectly with some demo data

### CODE REVIEW

**Comment by Brilator** [comment]
> Looks good, but I would change the organisation to CEPLAS or DataPLANT.

I did that to prevent tagging them as "curated" nor "CEPLAS" + being able to /o search for the demo ones

> Also not sure if we need a subdirectory for every type of template.

true

**Comment by Freymaurer** [comment]
I have an issue with this template. It says "Plant growth" as name, but is meant as demo template only? Ah user searching for plant growth templates will find this easily, whereas the "demo_dataplant" can easily be missed.

My suggestion is to fully commit to this plant growth template and make it DataPLANT curated.

**Comment by Brilator** [comment]
> I have an issue with this template. It says "Plant growth" as name, but is meant as demo template only? A user searching for plant growth templates will find this easily, whereas the "demo_dataplant" can easily be missed.
> 
> My suggestion is to fully commit to this plant growth template and make it DataPLANT curated.

puh ok..

**Comment by Brilator** [comment]
Fair enough. I was a bit reserved storing it as "curated". But since it's not tagged as GEO-compliant it'll be fine.

**Comment by Freymaurer** [comment]
Sorry i think i misscommunicated my issue. Currently we already have the very bloated plant growth template. Why not split it into smaller, more specific templates and give them the appropriate names. So we don't end up with multiple Plant growth templates.

image

I am very sorry, i know i am being pedantic, but if we have concise templates these should easily also be usable for demo purposes. In my opinion, if it does not feel good to present a template the users will propably not like them too.

**Comment by Brilator** [comment]
I almost agree twice: yes, I'd prefer a template, that's not just for demo and yes, the big plant growth chunk needs to be broken down. But that's not an easy one. 
And besides, for a good demo I'd still want an extra one, even though this honestly is a bit fake - tailoring the template to exactly one very minimized dataset, just so we're not ending up with too many empty columns.

**Comment by Brilator** [comment]
Btw, the duplicate use of "plant growth" also comes from the decision not to directly delete the old templates. But I can rename the other one.

**Comment by Martin-Kuhl** [comment]
I agree with both of you. I would not delete or break down the "old" plant growth as this could also be of advantage in use cases with multiple assays and multiple data repositories. 
In my opinion the way to go here are concise name, e.g., "plant growth - CEPLAS" or "plant growth - teaching".

**Pull request merged**
