### PR TITLE
Create MPIMP_Fernie_Metabolite_Extraction.xlsx

### PR DESCRIPTION
**Pull request by micwij**
In 71fb78ecef2cc82f1e3f22a93d3cd0b7eacab6ae I added a metabolite extraction protocol as mentioned in #67 . Let me know what you think.

### CODE REVIEW

**Review by Brilator — APPROVED** [review]

**Comment by Freymaurer** [comment]
Why is this approved and not merged @Brilator ?

**Comment by Brilator** [comment]
We've had the rule in other repos, that PRequesters merge themselves and delete the branch. 
But we can also arrange that one of us (e.g. you, me, Oliver?) moderates / admins this repo.

**Comment by Freymaurer** [comment]
I recommend always you merging as the maintanier 👍

**Comment by Brilator** [comment]
Well... now all these three templates failed and I have to dig into it :D

**Comment by micwij** [comment]
Thanks for checking @Freymaurer and thanks for taking care of it @Brilator. Sorry, if I made a mistake. Were you able to find the error already? Let me know if I can help.
I am happy to try to merge my own PRs in the future but I do not have write access in this repo yet.
Maybe you can let me know once everything is fine. Then I would delete the branches and close the corresponding issues.

**Comment by Freymaurer** [comment]
@micwij all good! The new template logic was able to parse everything just fine!

**Pull request merged**
