### PR TITLE
Adding a new template for Study files for TRR341 Phenotypic experiments

### PR DESCRIPTION
**Pull request by JulieTRR341**

### CODE REVIEW

**Comment by JulieTRR341** [comment]
@Brilator

**Comment by Brilator** [comment]
Hi @JulieTRR341, 

in your swate table, the first row had "user-specific" filled out as ontology references for the Protocol Type "Watering". 
This currently throws an error; so I removed it. 

Protocol Type | Term Source REF (EFO:0000683) | Term Accession Number (EFO:0000683)
--------------|-------------------------------|------------------------------------
Watering | user-specific | user-specific
Watering |  | 
Watering |  | 
Watering |  | 
Watering |  |

**Comment by Brilator** [comment]
Hey @Zerskk, can you check swobup? 
This PR / merged template did not trigger the swobup commit report email and the template is not available from Swate. Thanks!

**Comment by Brilator** [comment]
I've just triggered swobup by ticking up the version. This seemed to work.

**Comment by Brilator** [comment]
@JulieTRR341, congratulations to your first Swate template 🥳. It's now online and findable in Swate. 
The next one will be easier ;).

**Comment by JulieTRR341** [comment]
@Brilator Thanks :) I just added many more, they were definitely easier. If those work, I have all of them to work on my Mock ARC now

**Pull request merged**
