### PR TITLE
replaced nfdi4pso terms in next generation sequencing template

### PR DESCRIPTION
**Pull request by StellaEggels**

### CODE REVIEW

**Comment by StellaEggels** [comment]
#105 @Freymaurer added accession numbers to the ambiguous tags and changed similar tags to be identical. (I couldn't figure out how to open a separate pull request with one already open, so it is combined with the previous one.)

**Comment by Freymaurer** [comment]
> #105 @Freymaurer added accession numbers to the ambiguous tags and changed similar tags to be identical. (I couldn't figure out how to open a separate pull request with one already open, so it is combined with the previous one.)

Thanks alot @StellaEggels ! Did you, by any chance, also resolve issue #106 ? If yes we could close both and i could add an additional quality control pipele tomorrow #107

**Comment by StellaEggels** [comment]
I didn’t resolve issue #106 yet, because I was unsure about two things: 1. If in the Excel version the ER tags aren’t currently shown in the search, but only the "normal" tags, should they really be deleted from the normal tags yet? And 2. If the templates are not really “repository templates”, should we really add a repository as ER tag? If yes, I can quickly do that tomorrow so you can add the pipeline step.

**Comment by Freymaurer** [comment]
> I didn’t resolve issue #106 yet, because I was unsure about two things: 1. If in the Excel version the ER tags aren’t currently shown in the search, but only the "normal" tags, should they really be deleted from the normal tags yet? And 2. If the templates are not really “repository templates”, should we really add a repository as ER tag? If yes, I can quickly do that tomorrow so you can add the pipeline step.

Maybe @Brilator can give more insight regarding this topic :relaxed:

**Comment by Brilator** [comment]
Sorry for being late to the party. 
> 2. If the templates are not really “repository templates”, should we really add a repository as ER tag? If yes, I can quickly do that tomorrow so you can add the pipeline step.

Some ER tags are still a left-over from when we wanted to design templates in a modular fashion: you would combine multiple templates (e.g. growth, extraction, assay) to submit to one ER. In this case growth could be microbes or plants

**Pull request merged**
