### PR TITLE
Re-work of the MIAPPE template

### PR DESCRIPTION
**Pull request by Hannah-Doerpholz**
I re-made the MIAPPE template ONLY ever opening it in excel web. I hope that this can be properly read and made available in SWATE. The open issue is #47 .

### CODE REVIEW

**Review by Brilator — APPROVED** [review]

**Comment by Brilator** [comment]
> I re-made the MIAPPE template ONLY ever opening it in excel web. 

If I remember correctly, I fixed this issue at some point. 

The current file might throw an error. If the bug still exists, I think `Protocol REF` column can only contain all the same values (or all empty).

**Comment by Brilator** [comment]
So, feel free to merge and if it throws an error. Fill out that column completely.

**Comment by Brilator** [comment]
Two minor suggestions: 
- you might want to tick up the version in the metadata: Version | 1.0.0
- consider renaming the table sheet from "Tabelle1" to something more meaningful

**Comment by Hannah-Doerpholz** [comment]
I changed the table name and filled out the Protocol REF column in my branch to avoid getting errors from that. Since I don't have write access to this repo, could someone else push the changes (or grant me write access for this)?

**Comment by Hannah-Doerpholz** [comment]
No, those two were an accident. I didn't realize I wasn't editing in my fork. The new version is currently only in the feature brach of my fork. Unfortunately I'm not super familiar with contributing to repos that aren't mine.

**Comment by omaus** [comment]
I'm confused. This PR is from your fork's branch with the name "feature". Is this the wrong branch? Is there another feature branch?
You can also open a new PR from your new feature branch (if I understood you correctly) to upstream's main branch.

**Comment by Hannah-Doerpholz** [comment]
Sorry, I got a bit confused the last time. I added the changes I wanted to the feature branch in this PR (and that is the only feature branch). I just need someone to merge this PR

**Pull request merged**
